### PR TITLE
allow getProperties and setProperties for component integration tests

### PR DESCRIPTION
**Pull request by CodeOfficer**
Is this worth testing? O.o

### CODE REVIEW

**Comment by rwjblue** [comment]
> Is this worth testing?

Only if you don't want it removed as "unused" in a future refactor :stuck_out_tongue_closed_eyes:

**Comment by rwjblue** [comment]
Also, :+1: on this, maybe we should add `getProperties` too?

**Comment by pangratz** [comment]
I was about to submit such a PR. I think this is a useful addition.

> maybe we should add getProperties too?

:+1:

**Comment by CodeOfficer** [comment]
that work for ya?

**Comment by rwjblue** [comment]
Test failures were fixed in https://github.com/switchfly/ember-test-helpers/pull/79, restarting Travis build.

**Comment by rwjblue** [comment]
Thank you!

**Comment by rwjblue** [comment]
Released in ember-qunit@0.4.2.

**Comment by pangratz** [comment]
Thanks @CodeOfficer

**Pull request merged**
