### PR TITLE
Remove isolatedContainer and use Ember.Application.buildRegistry.

### PR DESCRIPTION
**Pull request by rwjblue**
The isolatedContainer was way to finicky and caused breakage any time Ember
or Ember Data decided to change what the default contents should be.

This replaces the `isolatedContainer` with the container built by
`Ember.Application.buildRegistry` (or `.buildContainer`) which has been
available since 1.0.0.  `.buildRegistry` does result in a container that is
fully fleshed out but it also has a resolver attached, so in the
non-integration case we replace that resolver with an empty function.

### CODE REVIEW

**Comment by rwjblue** [comment]
This should fix #46 and possibly #41.

**Comment by rwjblue** [comment]
FYI - this test suite checks Ember 1.10, 1.11, release (1.12), beta (future 1.13), and canary (future 2.0.0).

@dgeb - I'd like your feedback/review on this one...

**Comment by rwjblue** [comment]
@dgeb - Ping?

**Comment by dgeb** [comment]
@rwjblue sorry for the delay - will review tonight or tomorrow morning!

**Comment by dgeb** [comment]
@rwjblue what do you think of exporting separate methods `buildRegistry` and `buildContainer`, where `buildContainer` takes a `registry` as an argument?

**Comment by rwjblue** [comment]
@dgeb - Seems OK to me, what would the purpose/result be?  Just to replace the `isolatedContainer` export?

**Comment by dgeb** [comment]
@rwjblue I was thinking that it might be useful to be able to build multiple containers from the same registry. But anyway, this is all internal at this point, and my preference is to [reform all of this](https://github.com/emberjs/rfcs/pull/46) so that tests don't even deal with registries and containers, so I'm :+1: if you just want to merge now and refactor later ...

**Comment by rwjblue** [comment]
@dgeb - Thanks for reviewing!

**Pull request merged**
