### PR TITLE
Prefer Ember.assign over Ember.merge

### PR DESCRIPTION
**Pull request by martndemus**
See: http://emberjs.com/blog/2016/04/11/ember-2-5-released.html#toc_code-ember-assign-code

### CODE REVIEW

**Comment by bendemboski** [comment]
Yes please!

**Comment by AmilKey** [comment]
@rwjblue merge plz

**Comment by simonihmig** [comment]
👍

**Comment by danjamin** [comment]
👍

**Comment by trianglegrrl** [comment]
Whassup with the loader.js test failure? I just created almost exactly the same pull request (maybe exactly the same) and am having the same issue with loader.js.

**Comment by rwjblue** [comment]
loader moved its location, and our local build tooling is using the wrong path

**Pull request merged**
